[0_no-mergify]
color = "f0f854"
name = "0_no-mergify"
description = "自動マージOFF"

["1-ステータス: 1-待機中"]
color = "26afd9"
name = "1-ステータス: 1-待機中"
description = "待機中"

["1-ステータス: 2-作業中"]
color = "1fada2"
name = "1-ステータス: 2-作業中"
description = "作業中"

["1-ステータス: 3-作業完了"]
color = "22c373"
name = "1-ステータス: 3-作業完了"
description = "作業完了"

["1-ステータス: 4-作業中止"]
color = "4d807a"
name = "1-ステータス: 4-作業中止"
description = "作業中止"

["1-ステータス: 5-重複"]
color = "336699"
name = "1-ステータス: 5-重複"
description = "Issueの重複"

["1-ステータス: 6-保留"]
color = "4f767d"
name = "1-ステータス: 6-保留"
description = "保留"

["2-優先度: 1-最優先"]
color = "ff6666"
name = "2-優先度: 1-最優先"
description = "すぐさま取り組む必要がある程度"

["2-優先度: 2-高"]
color = "ff8a65"
name = "2-優先度: 2-高"
description = "早く取り組む必要がある程度"

["2-優先度: 3-中"]
color = "ffd166"
name = "2-優先度: 3-中"
description = "なるべく早く取り組む必要がある程度"

["2-優先度: 4-低"]
color = "dce775"
name = "2-優先度: 4-低"
description = "いつか取り組む必要がある程度"

["2-優先度: 5-最低"]
color = "81c785"
name = "2-優先度: 5-最低"
description = "余裕があれば取り組む程度"

["3-作業量: 1-膨大"]
color = "ff6666"
name = "3-作業量: 1-膨大"
description = "見出し8個～"

["3-作業量: 2-多"]
color = "ff8a65"
name = "3-作業量: 2-多"
description = "見出し6個～7個"

["3-作業量: 3-中"]
color = "ffd166"
name = "3-作業量: 3-中"
description = "見出し3個～5個"

["3-作業量: 4-少"]
color = "dce775"
name = "3-作業量: 4-少"
description = "見出し1個～2個"

["3-作業量: 5-ほぼ無し"]
color = "81c785"
name = "3-作業量: 5-ほぼ無し"
description = "見出し1個"

["依存関係"]
color = "2c71bf"
name = "依存関係"
description = "dependabot用"
