name: "記事案"
description: "新規記事作成"
title: "Article: "
labels: ["1-ステータス: 1-待機中"]
assignees: ["SoniPana"]


body:
  - type: checkboxes
    attributes:
      label: 0.ラベル付け
      description: ラベルを付け終えたらチェック
      options:
        - label: ①ステータス  状態を表すラベル
          required: true
        - label: ②優先度  優先度を表すラベル(任意)
        - label: ③作業量  想定される作業量を表すラベル(任意)

  - type: textarea
    attributes:
      label: 1.見出し
      description: >
        記事の見出し
      placeholder: >
        例)- 【GAS】Imgurに画像を投稿してくれるLINE Botの作成
    validations:
      required: true


  - type: textarea
    attributes:
      label: 2.内容
      description: >
        記事の内容
      placeholder: >
        - GASでImgurに画像を投稿するLINE Botを作成する
    validations:
      required: true

  - type: textarea
    attributes:
      label: 3.関連記事(任意)
      description: >
        関連する記事
      placeholder: >
        - #1

  - type: textarea
    attributes:
      label: 4.Todo(任意)
      description: >
        想定されるタスク
      placeholder: >
        - [ ] ImgurのAPIキーの取得
        - [ ] LINE Botの作成

  - type: textarea
    attributes:
      label: 5.メモ(任意)
      description: >
        memo
